baseURL = 'https://platelminto.com/'
languageCode = 'en-gb'
title = 'Hello!'
theme = 'archie'

paginate=10 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "i write stuff sometimes"
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/platelminto/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/pytxl/"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

