#!/bin/sh

. ./.env

hugo && rsync -avz -e "ssh -p ${PORT}" --delete public/ "${USER}"@"${HOST}":"${DIR}" # this will delete everything on the server's target folder, then copy the contents of public/

exit 0
